//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThueXeOto.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class Khach
    {
        public Khach()
        {
            this.HopDongs = new HashSet<HopDong>();
        }
    
        public int MaKhach { get; set; }
        [Display(Name = "Họ Tên")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
        public string TenKhach { get; set; }
        [Display(Name = "Địa Chỉ")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
        public string DiaChi { get; set; }
        [Display(Name = "Chứng Minh Nhân Dân Số")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
        public string CMTND { get; set; }
        [Display(Name = "Điện Thoại")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
        public string SoDT { get; set; }
        [Display(Name = "Tài Khoản")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
        public string SoTK { get; set; }
        [Display(Name = "Ngân Hàng")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
        public string NganHang { get; set; }
        [Display(Name = "Cơ Quan")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
        public string TenCQ { get; set; }
        [Display(Name = "Tên Đăng Nhập")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
        public string TaiKhoan { get; set; }
        [Display(Name = "Mật Khẩu")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
        public string MatKhau { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
        public string email { get; set; }
    
        public virtual ICollection<HopDong> HopDongs { get; set; }
    }
}
