//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThueXeOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.ChiTietHopDongs = new HashSet<ChiTietHopDong>();
            this.HoaDon_TTT = new HashSet<HoaDon_TTT>();
            this.SoXes = new HashSet<SoXe>();
        }
    
        public string SoHD { get; set; }
        public string MaKhach { get; set; }
        public System.DateTime Ngay { get; set; }
        public string ND_CongViec { get; set; }
        public string Dongia_HTTT { get; set; }
        public string Trachnhiem { get; set; }
        public string DK_CuThe { get; set; }
        public string DK_Chung { get; set; }
        public Nullable<double> TienTamUng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHopDong> ChiTietHopDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon_TTT> HoaDon_TTT { get; set; }
        public virtual Khach Khach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoXe> SoXes { get; set; }
    }
}
